### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by tenstad** [rdfostrich/ostrich#4]
Commit e645f54ccb60e73bf5fe05c0a9da56bf3685a6ef

`docker build -t ostrich .`

```
Step 21/27 : RUN cd /opt/ostrich/deps/hdt/hdt-lib && sed -i "s/#KYOTO_SUPPORT=true/KYOTO_SUPPORT=true/" Makefile
 ---> Running in c7f115966d5d
/bin/sh: 1: cd: can't cd to /opt/ostrich/deps/hdt/hdt-lib
The command '/bin/sh -c cd /opt/ostrich/deps/hdt/hdt-lib && sed -i "s/#KYOTO_SUPPORT=true/KYOTO_SUPPORT=true/" Makefile' returned a non-zero code: 2
```

**Comment by rubensworks** [comment]
@opelgrin Do you have any idea?

**Comment by tenstad** [comment]
The `/opt/ostrich/deps/hdt` is empty, but I do not know why or what should have been there.

**Comment by tenstad** [comment]
My bad, forgot to init the submodules: `git submodule update --init`. Could maybe add it to the readme.

**Comment by rubensworks** [comment]
Glad to hear it's fixed :-)
Additions to the README are definitely welcome!
